# Lab: Building a Reproducible Analysis Workflow

Choose your own documented dataset, develop three distinct research questions, and answer each using the six-step workflow from the Pokémon lecture. You may reuse your visual thinking dataset, but develop new questions rather than repeat its single-feature charts.

## Learning goals

- Develop three questions that can be answered with your chosen data.
- Inspect and document a dataset using its data dictionary.
- Select, group, summarize, or calculate features with Pandas.
- Connect displayed evidence, contextual sanity checks, conclusions, and limitations.

## The reproducible analysis workflow

1. **Question:** What do we want to learn?
2. **Data:** Which observations and features can help answer it?
3. **Evidence:** What should we calculate and display to answer the question?
4. **Check:** Does the result make sense in context? Do a few original records support the meaning of the calculation?
5. **Conclusion:** What claim is supported?
6. **Limitation:** What should we avoid concluding?

## Using AI tools responsibly

You may use AI to ask questions, debug code, or receive feedback. You remain responsible for understanding the work and checking suggestions. Disclose whether you used AI in the final reflection.

## Find and document your dataset

Choose your own documented CSV dataset from [Kaggle](https://www.kaggle.com/datasets) or another reputable source. You may reuse the dataset from the visual thinking lab. Choose data with:

- a clearly identified publisher or creator;
- a data dictionary or documentation explaining observations and features;
- at least one categorical and one quantitative feature;
- enough information to answer three distinct questions involving calculations or comparisons;
- content appropriate to share in class, without private or personally identifying information; and
- a manageable file size.

Save the CSV in this notebook's `data` folder. Use a descriptive DataFrame name ending in `_df` throughout your analysis.

**What is the dataset's title, publisher or creator, direct source URL, and data dictionary URL or location?**

Your answer: I reused the Iris Plants Database by R. A. Fisher that I used in the previous lab, which is hosted by the UCI Machine Learning Repository.

- Source: [UCI Iris](https://archive.ics.uci.edu/dataset/53/iris)
- Original data: [iris.data](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data)
- Data dictionary: [iris.names](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.names)
- Local CSV: `data/iris.csv`
- Citation: Fisher, R. (1936). *Iris* [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C56C76. CC BY 4.0.

**Briefly describe the dataset and relevant features using its documentation. What does one row represent? Include units and the meaning of blank values where documented.**

Your answer: Each row is one iris plant. The file has 150 plants from three species. The four measurements are sepal length, sepal width, petal length, and petal width, all in centimeters. The species column identifies the plant's species. The dictionary says there are no missing values. No special blank-value codes are listed. The CSV uses descriptive column names added in the first lab, including `species` for the original class column. The measurement values were not changed.

## Plan three investigations

Develop three distinct research questions about your dataset. Each must require a calculation or comparison, not simply looking up a value. Consider grouped averages, percentages meeting a condition, or comparisons between features, as in the lecture; adapt the questions to what your data means. Complete all six steps for each question. Record each prediction before running its calculations.

## Investigation 1

### Step 1: Question

State a specific question that your dataset can answer. Define any important groups or comparisons.

**What is your research question 1?**

Your answer: Which of the three iris species has the highest average petal length? I will use the mean and show the number of plants in each species.

### Prediction — before calculating

**What do you predict the result will be, and why?**

Your answer: I expect the averages to be fairly close because all three groups are iris plants. I will check whether the species differ more than I expect.

### Step 2: Data

Import Pandas and load your CSV into a descriptively named DataFrame ending in `_df`. Inspect the data once here, using separate cells for each operation.

In [1]:
import pandas as pd

In [2]:
iris_df = pd.read_csv("data/iris.csv")

In [3]:
iris_df.head()

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

In [4]:
iris_df.tail()

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
iris_df.shape

(150, 5)

In [6]:
iris_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sepal_length_cm  150 non-null    float64
 1   sepal_width_cm   150 non-null    float64
 2   petal_length_cm  150 non-null    float64
 3   petal_width_cm   150 non-null    float64
 4   species          150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.9 KB

In [7]:
iris_df.isnull().sum()

sepal_length_cm    0
sepal_width_cm     0
petal_length_cm    0
petal_width_cm     0
species            0
dtype: int64

**Which observations and features will you use? Explain relevant units, any filtering, and how you will handle missing or not-applicable values using the dictionary. For a percentage, define the denominator.**

Your answer: I will use all 150 plants, grouped by `species`, and their `petal_length_cm` values. Petal length is measured in centimeters. The dictionary reports no missing values, and the inspection will check that. No rows will be removed or missing values filled in.

### Step 3: Evidence

Write the code that answers your question. Break the analysis into separate cells for individual operations, as in the lecture, and add cells as needed. Display intermediate results where useful and the final result that answers the question. Explain any new calculated features. You may display a grouped summary directly without assigning it to a variable.

In [8]:
iris_df.groupby("species")["petal_length_cm"].agg(["count", "mean"])

                 count   mean
species
Iris-setosa         50  1.464
Iris-versicolor     50  4.260
Iris-virginica      50  5.552

In [9]:
iris_df.groupby("species")["petal_length_cm"].agg(["count", "mean"]).sort_values(
    "mean", ascending=False
)

                 count   mean
species
Iris-virginica      50  5.552
Iris-versicolor     50  4.260
Iris-setosa         50  1.464

**Which specific value or comparison answers your question? Explain how your calculations connect the selected data to that result.**

Your answer: Iris-virginica has the highest mean petal length at 5.552 cm. Iris-versicolor averages 4.260 cm and Iris-setosa averages 1.464 cm. Each group has 50 plants. The code groups plants by species, finds each mean, and sorts the results from highest to lowest.

### Step 4: Check

Perform a sanity check tied to the meaning of your question. Explain what values or patterns would make you suspicious and whether your result makes sense. Depending on the analysis, consider plausible values and units, whether indicators match original labels, or whether the ranges within comparison groups match their definitions. Use additional code only when it helps this check; do not simply repeat the initial row count or missing-value inspection. An unexpected result is a reason to investigate, not to change the result to fit your prediction.

In [10]:
iris_df.groupby("species").head(2)[["species", "petal_length_cm"]]

             species  petal_length_cm
0        Iris-setosa              1.4
1        Iris-setosa              1.4
50   Iris-versicolor              4.7
51   Iris-versicolor              4.5
100   Iris-virginica              6.0
101   Iris-virginica              5.1

In [11]:
iris_df.groupby("species")["petal_length_cm"].agg(["min", "max"])

                 min  max
species
Iris-setosa      1.0  1.9
Iris-versicolor  3.0  5.1
Iris-virginica   4.5  6.9

**What would make you suspicious, and why? Does your evidence make sense in context? Describe any issue you found and how you addressed it.**

Your answer: A negative petal length or a mean outside its species' minimum and maximum would be a warning sign. The displayed records use small positive values in centimeters. All three means fall within their group's range: 1.0 to 1.9 cm for setosa, 3.0 to 5.1 cm for versicolor, and 4.5 to 6.9 cm for virginica. Nothing in these checks points to a calculation error.

### Step 5: Conclusion

**Answer your research question in a sentence using the numerical evidence. How does it compare with your prediction?**

Your answer: Iris-virginica has the highest mean petal length at 5.552 cm, based on 50 plants. The means are farther apart than predicted, especially between setosa and the other two species.

### Step 6: Limitation

**What should a reader avoid concluding from this result, and why? Connect your limitation to this question and dataset.**

Your answer: This does not mean every virginica petal is longer than every versicolor petal. Their ranges overlap. These averages describe the plants in this file, not every iris plant.

## Investigation 2

### Step 1: Question

State a specific question that your dataset can answer. Define any important groups or comparisons.

**What is your research question 2?**

Your answer: What percent of the 150 plants have a sepal length greater than 6 cm? A value of exactly 6 cm will not count as greater than 6.

### Prediction — before calculating

**What do you predict the result will be, and why?**

Your answer: I expect fewer than half to be above 6 cm because that seems fairly long for one flower part. This is a guess to check against the measurements.

### Step 2: Data

Reuse the DataFrame and initial inspection from Investigation 1. Identify the observations and features relevant to this question; inspect additional features only if needed.

**Which observations and features will you use? Explain relevant units, any filtering, and how you will handle missing or not-applicable values using the dictionary. For a percentage, define the denominator.**

Your answer: I will use `sepal_length_cm` for all 150 plants. The denominator is all 150 plants, not just those above 6 cm. The cutoff is strictly greater than 6. The column has no missing values, so no rows need to be removed. I will create `sepal_over_6_cm`, where 1 means above 6 cm and 0 means 6 cm or less.

### Step 3: Evidence

Write the code that answers your question. Break the analysis into separate cells for individual operations, as in the lecture, and add cells as needed. Display intermediate results where useful and the final result that answers the question. Explain any new calculated features. You may display a grouped summary directly without assigning it to a variable.

In [12]:
iris_df["sepal_over_6_cm"] = (iris_df["sepal_length_cm"] > 6).astype(int)

In [13]:
sepal_over_6_count = iris_df["sepal_over_6_cm"].sum()

In [14]:
sepal_over_6_percent = sepal_over_6_count / len(iris_df["sepal_over_6_cm"]) * 100

In [15]:
print("Plants above 6 cm:", sepal_over_6_count)

Plants above 6 cm: 61

In [16]:
print("Total plants:", len(iris_df["sepal_over_6_cm"]))

Total plants: 150

In [17]:
print("Percent above 6 cm:", round(sepal_over_6_percent, 2))

Percent above 6 cm: 40.67

**Which specific value or comparison answers your question? Explain how your calculations connect the selected data to that result.**

Your answer: 61 of the 150 plants have a sepal length above 6 cm. That is 40.67%. The code marks each matching plant with 1, adds those values, divides by 150, and multiplies by 100.

### Step 4: Check

Perform a sanity check tied to the meaning of your question. Explain what values or patterns would make you suspicious and whether your result makes sense. Depending on the analysis, consider plausible values and units, whether indicators match original labels, or whether the ranges within comparison groups match their definitions. Use additional code only when it helps this check; do not simply repeat the initial row count or missing-value inspection. An unexpected result is a reason to investigate, not to change the result to fit your prediction.

In [18]:
iris_df[["sepal_length_cm", "sepal_over_6_cm"]].head(10)

   sepal_length_cm  sepal_over_6_cm
0              5.1                0
1              4.9                0
2              4.7                0
3              4.6                0
4              5.0                0
5              5.4                0
6              4.6                0
7              5.0                0
8              4.4                0
9              4.9                0

In [19]:
iris_df[iris_df["sepal_length_cm"] == 6][["sepal_length_cm", "sepal_over_6_cm"]]

     sepal_length_cm  sepal_over_6_cm
62               6.0                0
78               6.0                0
83               6.0                0
85               6.0                0
119              6.0                0
138              6.0                0

In [20]:
iris_df.groupby("sepal_over_6_cm")["sepal_length_cm"].agg(["min", "max"])

                 min  max
sepal_over_6_cm
0                4.3  6.0
1                6.1  7.9

**What would make you suspicious, and why? Does your evidence make sense in context? Describe any issue you found and how you addressed it.**

Your answer: I would be suspicious if a 6.0 cm sepal got a 1, or if a value above 6 got a 0. The 6.0 cm rows all have 0. The 0 group runs from 4.3 to 6.0 cm, and the 1 group runs from 6.1 to 7.9 cm. Those ranges match the rule, and 40.67% is between 0% and 100%.

### Step 5: Conclusion

**Answer your research question in a sentence using the numerical evidence. How does it compare with your prediction?**

Your answer: 61 of 150 plants, or 40.67%, have sepals longer than 6 cm. That supports the prediction that fewer than half would meet the cutoff.

### Step 6: Limitation

**What should a reader avoid concluding from this result, and why? Connect your limitation to this question and dataset.**

Your answer: This percentage depends on the 6 cm cutoff and the plants in this file. It does not show that 40.67% of all iris plants in nature have sepals above 6 cm.

## Investigation 3

### Step 1: Question

State a specific question that your dataset can answer. Define any important groups or comparisons.

**What is your research question 3?**

Your answer: What percent of plants have a petal length greater than, less than, or equal to their sepal width? I will compare the two measurements within each row. Equal means exactly equal.

### Prediction — before calculating

**What do you predict the result will be, and why?**

Your answer: I expect the greater-than group to be the largest and exact ties to be uncommon. These measure different parts of the flower, so I do not expect them to match often.

### Step 2: Data

Reuse the DataFrame and initial inspection from Investigation 1. Identify the observations and features relevant to this question; inspect additional features only if needed.

**Which observations and features will you use? Explain relevant units, any filtering, and how you will handle missing or not-applicable values using the dictionary. For a percentage, define the denominator.**

Your answer: I will use `petal_length_cm` and `sepal_width_cm` for all 150 plants. Both are measured in centimeters and have no missing values. Each plant will be counted once in Greater, Less, or Equal. Each percentage uses all 150 plants as its denominator. No rows will be removed.

### Step 3: Evidence

Write the code that answers your question. Break the analysis into separate cells for individual operations, as in the lecture, and add cells as needed. Display intermediate results where useful and the final result that answers the question. Explain any new calculated features. You may display a grouped summary directly without assigning it to a variable.

In [21]:
petal_greater = iris_df["petal_length_cm"] > iris_df["sepal_width_cm"]

In [22]:
petal_less = iris_df["petal_length_cm"] < iris_df["sepal_width_cm"]

In [23]:
petal_equal = iris_df["petal_length_cm"] == iris_df["sepal_width_cm"]

In [24]:
iris_df.loc[petal_greater, "petal_sepal_group"] = "Greater"

In [25]:
iris_df.loc[petal_less, "petal_sepal_group"] = "Less"

In [26]:
iris_df.loc[petal_equal, "petal_sepal_group"] = "Equal"

In [27]:
petal_sepal_summary_df = iris_df["petal_sepal_group"].value_counts().to_frame("plant_count")

In [28]:
petal_sepal_summary_df["percentage"] = petal_sepal_summary_df["plant_count"] / len(iris_df) * 100

In [29]:
petal_sepal_summary_df.round(2)

                   plant_count  percentage
petal_sepal_group
Greater                    100       66.67
Less                        50       33.33

In [30]:
print("Exact ties:", petal_equal.sum())

Exact ties: 0

**Which specific value or comparison answers your question? Explain how your calculations connect the selected data to that result.**

Your answer: Petal length is greater than sepal width in 100 plants, or 66.67%. It is less in 50 plants, or 33.33%. There are 0 exact ties, or 0%. The code compares the two measurements in each row, labels the result, and divides each group's count by all 150 plants. A separate count shows that no rows meet the equality condition.

### Step 4: Check

Perform a sanity check tied to the meaning of your question. Explain what values or patterns would make you suspicious and whether your result makes sense. Depending on the analysis, consider plausible values and units, whether indicators match original labels, or whether the ranges within comparison groups match their definitions. Use additional code only when it helps this check; do not simply repeat the initial row count or missing-value inspection. An unexpected result is a reason to investigate, not to change the result to fit your prediction.

In [31]:
iris_df["petal_sepal_difference_cm"] = iris_df["petal_length_cm"] - iris_df["sepal_width_cm"]

In [32]:
iris_df.groupby("petal_sepal_group")["petal_sepal_difference_cm"].describe()

                   count   mean       std  min    25%  50%  75%  max
petal_sepal_group
Greater            100.0  2.034  0.711836  0.5  1.475  2.0  2.5  4.3
Less                50.0 -1.954  0.389772 -2.9 -2.200 -1.9 -1.6 -1.0

In [33]:
iris_df.groupby("petal_sepal_group").head(2)[["petal_length_cm", "sepal_width_cm", "petal_sepal_group"]]

    petal_length_cm  sepal_width_cm petal_sepal_group
0               1.4             3.5              Less
1               1.4             3.0              Less
50              4.7             3.2           Greater
51              4.5             3.2           Greater

**What would make you suspicious, and why? Does your evidence make sense in context? Describe any issue you found and how you addressed it.**

Your answer: The Greater group should only have positive differences, the Less group should only have negative differences, and any Equal rows should have 0. Greater runs from 0.5 to 4.3 cm, while Less runs from -2.9 to -1.0 cm. The displayed records agree with their labels. There are no Equal rows. A wrong sign or a zero in the other groups would make me check the labels.

### Step 5: Conclusion

**Answer your research question in a sentence using the numerical evidence. How does it compare with your prediction?**

Your answer: 100 plants (66.67%) have petal length greater than sepal width, 50 (33.33%) have less, and 0 (0%) are equal. The greater-than group is the largest, as predicted. There were no exact ties.

### Step 6: Limitation

**What should a reader avoid concluding from this result, and why? Connect your limitation to this question and dataset.**

Your answer: This only compares petal length with sepal width. It does not show which plants are healthier or larger overall. It also does not describe all iris plants outside this file.

## AI-use reflection

**State whether you used an AI tool. If you did, describe one suggestion you checked and what you accepted, changed, or rejected. If you did not, state that you did not use one.**

Your answer: 
- **Tool used:** OpenAI ChatGPT.
- **What I asked it to help with:** I asked it to review my work after I had completed the analysis and check for any obvious issues.
- **One suggestion I checked against my code, chart, or output:** It suggested a few minor visual and formatting improvements to make the results easier to read. I checked the affected outputs to make sure the displayed values still matched my calculations.
- **What I accepted, modified, or rejected—and why:** I accepted the small presentation improvements because they made the results clearer without changing the analysis. I did not make any changes to my calculations or conclusions because the results were already consistent with the code and output.

## Submission checklist

- Include your chosen dataset, source, and dictionary reference.
- Complete three distinct questions, each with a prediction and all six workflow steps.
- Use a descriptive DataFrame name ending in `_df` and relative file paths.
- Restart the kernel and run all cells in order; verify that numerical claims match displayed output.
- Include a contextual sanity check, supported conclusion, and relevant limitation for each question.
- Complete every written response and the AI-use reflection.